services:
  mysql:
    image: mysql:8.0
    container_name: eyesonplants-mysql
    environment:
      MYSQL_ROOT_PASSWORD: koko992002
      MYSQL_DATABASE: EyesOnPlants
    ports:
      - "3307:3306"  # ✅ تم تصحيح المسافة هنا
    volumes:
      - mysql-data:/var/lib/mysql
      - ./EyesOnPlants.sql:/docker-entrypoint-initdb.d/EyesOnPlants.sql
    networks:
      - eyesonplants-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    container_name: eyesonplants-springboot
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/EyesOnPlants?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=koko992002
      - AI_SERVICE_URL=http://python-service:5000/predict
    ports:
      - "8080:8080"
    networks:
      - eyesonplants-network

  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: eyesonplants-python
    ports:
      - "5000:5000"
    volumes:
      - ./python-service:/app
    networks:
      - eyesonplants-network

networks:
  eyesonplants-network:
    driver: bridge

volumes:
  mysql-data:
