version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EyesOnPlants
      MYSQL_USER: root
      MYSQL_PASSWORD: koko992002
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: ./backend-java
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: koko992002
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/EyesOnPlants?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      AI_SERVICE_URL: http://python:5000/predict


  python:
    build: ./backend-python
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: EyesOnPlants
      DB_USER: root
      DB_PASS: koko992002

volumes:
  mysql_data:
